#!/usr/bin/env php
<?php
if(ob_get_level() == 0)
        ob_start();

ob_implicit_flush();

// Load the config to get the stomp details
require_once(__DIR__ . "/../config.php");

$stomp = new Stomp($stompServer, $stompUser, $stompPassword);
$stomp->subscribe("/topic/kills");
while(true)
{
        $frame = $stomp->readFrame();
        if(!empty($frame))
        {
                if(!empty($frame->body))
                {
                        $json = json_encode(json_decode($frame->body, true), JSON_NUMERIC_CHECK | JSON_UNESCAPED_SLASHES);
                        fwrite(STDOUT, $json . "\n");
                        ob_flush();
                        flush();
                }
                $stomp->ack($frame->headers["message-id"]);
        }
}
