#!/usr/bin/env php
<?php
if(ob_get_level() == 0)
        ob_start();

ob_implicit_flush();

// Load the config to get the stomp details
require_once(__DIR__ . "/../config.php");

$stomp = new Stomp($stompServer, $stompUser, $stompPassword);
$stomp->subscribe("/topic/kills");
while(true)
{
        $frame = $stomp->readFrame();
        if(!empty($frame))
        {
                if(!empty($frame->body))
                {
                        $data = json_decode($frame->body, true);
                        $map = json_encode(array("solarSystemID" => $data["solarSystemID"], "killID" => $data["killID"], "characterID" => $data["victim"]["characterID"], "corporationID" => $data["victim"]["corporationID"], "allianceID" => $data["victim"]["allianceID"], "shipTypeID" => $data["victim"]["shipTypeID"], "killTime" => $data["killTime"], "involved" => count($data["attackers"]), "totalValue" => $data["zkb"]["totalValue"], "pointsPrInvolved" => $data["zkb"]["points"]));

                        fwrite(STDOUT, $map."\n");
                        ob_flush();
                        flush();
                }
                $stomp->ack($frame->headers["message-id"]);
        }
}
